workspace(name = "ampvalidator")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_absl",
    strip_prefix = "abseil-cpp-master",
    urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],
)

http_archive(
    name = "com_google_googletest",
    sha256 = "7c719b5553add25783309e18e3fb2ae5c443b63c502e532118e1bc833f528745",
    strip_prefix = "googletest-a0ced33ac6df214966bb90ba036e0a5666dca14e",
    urls = ["https://github.com/google/googletest/archive/a0ced33ac6df214966bb90ba036e0a5666dca14e.zip"],  # 2019-01-07
)

http_archive(
    name = "com_googlesource_code_re2",
    sha256 = "69ddc658df387b4d2d51c6fe2d0c62933220d17e1465e4071a5673c01c9bcd2d",
    strip_prefix = "re2-11073deb73b3d01018308863c0bcdfd0d51d3e70",
    urls = [
        "https://github.com/google/re2/archive/11073deb73b3d01018308863c0bcdfd0d51d3e70.tar.gz",
    ],
)

http_archive(
    name = "com_github_gflags_gflags",
    strip_prefix = "gflags-master",
    urls = ["https://github.com/gflags/gflags/archive/master.zip"],
)

http_archive(
    name = "com_github_re2",
    strip_prefix = "re2-master",
    urls = ["https://github.com/google/re2/archive/master.zip"],
)

http_archive(
    name = "com_github_glog",
    strip_prefix = "glog-master",
    urls = ["https://github.com/google/glog/archive/master.zip"],
)

http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-master",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/master.zip"],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()

local_repository(
    name = "amphtml-extensions",
    path = "../../../extensions/",
)

local_repository(
    name = "validator",
    path = "../../",
)

local_repository(
    name = "htmlparser",
    path = "../htmlparser/",
)
